### ISSUE TITLE
query batch completion by batch_id?

### ISSUE THREAD

**Issue by maia** [cdale77/active_job_status#10]
What is the suggested way to query batch completion with a given batch_id? 

My use case: I have a ActiveJob class that queries many URLs, one after the other. Only *after* all URLs have been queried, I want to run a second ActiveJob class. Both these jobs are called from a rake task.

__My approach:__
 1. enqueue all jobs of the first class, return their job_ids
 2. create a unique batch_id 
 3. create ActiveJobStatus::JobBatch.new with this batch_id and the job_ids
 4. call #perform_later on the second job class, pass the batch_id
 5. in that second job class find the batch, query if it's completed
 6. if completed, run the job, if not, reschedule it

__The problems:__
 1. There is ActiveJobStatus::JobBatch.find(batch_id:), but it chains #to_a onto #fetch without checking for nil.
 2. This (btw, undocumented) method returns a job_id array, not a batch object. Therefor one can't use the #completed? method but has to use a custom method.

…or do you have a different suggestion on how to ensure the execution order of multiple ActiveJob classes? Thanks!

**Comment by cdale77** [comment]
Hi @maia thanks for drawing these things to my attention. I'll fix the unsafe #to_a method. I'm not sure I'll have the time in the near future to work on documentation or to modify the find method to return an object. That makes sense, but I would want to think about how it would impact the Redis compatibility we have in there. 

I don't have a ton of time to work on this, so I'd be more than happy to entertain some pull requests if you'd like to contribute on those other matters. Glad you find at least the idea of this library helpful. 

It terms of ensuring execution order of jobs, I wasn't really thinking of that when I made this library, so I don't have any good thoughts for you right off the top of my head. Sorry!

**Comment by cdale77** [comment]
@maia Just looking at this again, and you bring up some excellent points. I'm going to leave this open, to track the following changes to be made:

1) Check for nil before calling to_a: https://github.com/cdale77/active_job_status/blob/master/lib/active_job_status/job_batch.rb#L44

2) Refactor ActiveJobStatus::JobBatch.find to return an instance of the class, not an array. Thanks for pointing out that improvement, it would make the library a lot more useful

**Comment by cdale77** [comment]
Re #1 - in ruby nil.to_a returns an empty array. Interestingly I didn't realize that immediately, but I had a spec for this case:
https://github.com/cdale77/active_job_status/blob/master/spec/job_batch_spec.rb#L67

The spec had an incorrect description, so I've updated it. So the #to_a method issue is resolved.

**Comment by cdale77** [comment]
#2 is fixed in the PR that auto-closed this
