### ISSUE TITLE
batch.completed? returning false for completed jobs

### ISSUE THREAD

**Issue by arachman** [cdale77/active_job_status#17]
batch.completed? seems to be returning false even when all the jobs in the batch has :completed status.

`[33] pry(main)> batch.completed?
=> false`

`[34] pry(main)> batch.job_ids.each { |jid|
[34] pry(main)*   job_status = ActiveJobStatus.fetch(jid)  
[34] pry(main)*   puts job_status.inspect  
[34] pry(main)* }  
#<ActiveJobStatus::JobStatus:0x007fbe03a23ca8 @status=:completed>
#<ActiveJobStatus::JobStatus:0x007fbe0402b150 @status=:completed>
#<ActiveJobStatus::JobStatus:0x007fbe039fbdc0 @status=:completed>
#<ActiveJobStatus::JobStatus:0x007fbe039bc1c0 @status=:completed>
#<ActiveJobStatus::JobStatus:0x007fbe0391efb0 @status=:completed>
#<ActiveJobStatus::JobStatus:0x007fbe03954db8 @status=:completed>
#<ActiveJobStatus::JobStatus:0x007fbe038c0d98 @status=:completed>
#<ActiveJobStatus::JobStatus:0x007fbe03849658 @status=:completed>
#<ActiveJobStatus::JobStatus:0x007fbe03838330 @status=:completed>
#<ActiveJobStatus::JobStatus:0x007fbe08f62728 @status=:completed>
#<ActiveJobStatus::JobStatus:0x007fbe0b5c3228 @status=:completed>
#<ActiveJobStatus::JobStatus:0x007fbe0b427360 @status=:completed>`

**Comment by cdale77** [comment]
Thanks for this! It was an implementation error on my part. Should be fixed in https://github.com/cdale77/active_job_status/commit/e776d0fc33f0cbcc2edca577aa3cd4e48d1bcbd0 and included in v1.2, which I just published.

**Comment by arachman** [comment]
@cdale77 Thanks for addressing this. Removing my 'monkey patch' on my code.
