### ISSUE TITLE
TrackableJob polutes the global namespace

### ISSUE THREAD

**Issue by jcoyne** [cdale77/active_job_status#7]
How about putting it in the ActiveJob namespace?  

```ruby 
class MyJob < ActiveJob::TrackableJob
...
end
```

**Comment by cdale77** [comment]
Ah, good point, thanks! Your solution is probably a good one, but I wonder if I shouldn't have just included it in the ActiveJobStatus namespace like I did with the other classes? AFAIK I can do that and still inherit from ActiveJob, and that gives me a safer namespace. Thoughts?

**Comment by cdale77** [comment]
Also thanks for your interest and for pointing this out!

**Comment by jcoyne** [comment]
Sure. As long as it's not the root.

**Comment by cdale77** [comment]
Just an update, I've been very busy but will address this shortly. I'll probably also increment the version number of the gem.

**Comment by cdale77** [comment]
This was resolved in the following commit. Closing. @jcoyne thanks for the ticket!

https://github.com/cdale77/active_job_status/commit/900c801634a7203a6a455f51d326255bf344d9aa
